apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-webapp
  template:
    metadata:
      labels:
        app: todo-webapp
    spec:
      containers:
      - name: todo
        image: yogeshrajendran/todo-app:latest
        ports:
        - containerPort: 80